# Generated by Django 3.1.7 on 2021-03-12 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20210311_0050'),
        ('store', '0005_auto_20210311_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='profile.profile'),
        ),
    ]
