# Generated by Django 3.1.7 on 2021-03-01 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=100, verbose_name='Nome do Estabelecimento')),
                ('tax_document', models.CharField(max_length=100, verbose_name='CPF ou CNPJ')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('photo', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=False, null=True, verbose_name='Está ativo')),
                ('can_pick_up_in_store', models.BooleanField(default=False, null=True, verbose_name='Pode retirar na loja')),
                ('slug', models.SlugField(default=None, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
