# Generated by Django 3.1.7 on 2021-03-05 02:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210304_2308'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0002_auto_20210304_2157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Client',
        ),
    ]
