# Generated by Django 3.2.19 on 2023-06-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateField(blank=True, default=None),
        ),
    ]
