# Generated by Django 3.1.7 on 2021-03-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_sufix', models.CharField(help_text='api.zapei.com.br/url_sufix', max_length=100, verbose_name='Sufixo do cliente')),
                ('token_zapei', models.TextField(help_text="Na sua conta Zapei, clique em 'olá...' no canto superior direito, escolha integrações, e clique em Gerar Token", verbose_name='Token Zapei')),
            ],
        ),
    ]
