# Generated by Django 3.1.7 on 2021-03-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationdata',
            options={'verbose_name': 'Integração', 'verbose_name_plural': 'Integrações'},
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='url_sufix',
            field=models.CharField(help_text="https://zapei-api.herokuapp.com/integracao/'Sufixo do cliente'/", max_length=100, verbose_name='Sufixo do cliente'),
        ),
    ]
