# Generated by Django 3.1.7 on 2021-03-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20210304_0049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntegrationData',
            new_name='RdStationZapei',
        ),
    ]
