# Generated by Django 3.1.7 on 2021-03-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20210304_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rdstationzapei',
            options={'verbose_name': 'Integração RdStationZapei', 'verbose_name_plural': 'Integrações RdStationZapei'},
        ),
        migrations.AlterField(
            model_name='rdstationzapei',
            name='token_zapei',
            field=models.TextField(help_text='Acesse https://painel.zapei.com.br/admin/integrations > clique em Gerar Token', verbose_name='Token Zapei'),
        ),
        migrations.AlterField(
            model_name='rdstationzapei',
            name='url_sufix',
            field=models.CharField(help_text="Acesse https://app.rdstation.com.br/integracoes/webhooks > clique em Criar Webhook > Escolha um nome, no campo GATILHO selecione: Conversão, no campo URL coloque: https://zapei-api.herokuapp.com/integrations/rd-zapei/'Sufixo do cliente'/, Eventos de Conversão pode ficar Vazio", max_length=100, verbose_name='Sufixo do cliente'),
        ),
    ]
